public class ErrorHandlingAndException {
    public static void main(String[] args){


//        Exception Demo
//        int[] numbers = {1, 2, 3};
//        System.out.println(numbers[999]);


//        Our very own exception
//        throw new Exception("Something bad happened!");

//        do note
//        System.out.println("after the throw statement");

//        try {
//            System.out.println("Let's see...");
//            int result = 1 / 0;
//            System.out.println("I can divide by zero!");
//        } catch (ArithmeticException e) {
//            System.out.println("Math still works!");
//        }
//
//        int[] numbers = {1, 2, 3};
//        int x;
//
//        try {
//            x = numbers[100];
//        } catch (ArrayIndexOutOfBoundsException e) {
//            System.out.println("Caught an array index exception!");
//        } catch (Exception e) {
//            System.out.println("Caught a generic exception!");
//        } finally {
//            System.out.println("This will always run.");
//        }





    }
}
